// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: waveshare43-minimal

#ifndef _WAVESHARE43_MINIMAL_UI_H
#define _WAVESHARE43_MINIMAL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t * ui_Main;
void ui_event_LEDButton(lv_event_t * e);
extern lv_obj_t * ui_LEDButton;
extern lv_obj_t * ui_Label1;
void ui_event_CastButton(lv_event_t * e);
extern lv_obj_t * ui_CastButton;
extern lv_obj_t * ui_Label5;
// SCREEN: ui_LEDs
void ui_LEDs_screen_init(void);
extern lv_obj_t * ui_LEDs;
void ui_event_Button22(lv_event_t * e);
extern lv_obj_t * ui_Button22;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Button23;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Button24;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Button25;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Button26;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Button27;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Button28;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Button29;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Button30;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Button31;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Button32;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Button33;
extern lv_obj_t * ui_Label33;
// SCREEN: ui_Cast
void ui_Cast_screen_init(void);
extern lv_obj_t * ui_Cast;
extern lv_obj_t * ui_Button53;
extern lv_obj_t * ui_Label53;
extern lv_obj_t * ui_Button54;
extern lv_obj_t * ui_Label54;
extern lv_obj_t * ui_Button55;
extern lv_obj_t * ui_Label55;
extern lv_obj_t * ui_Button56;
extern lv_obj_t * ui_Label56;
extern lv_obj_t * ui_Button57;
extern lv_obj_t * ui_Label57;
extern lv_obj_t * ui_Button58;
extern lv_obj_t * ui_Label58;
extern lv_obj_t * ui_Button59;
extern lv_obj_t * ui_Label59;
void ui_event_Button60(lv_event_t * e);
extern lv_obj_t * ui_Button60;
extern lv_obj_t * ui_Label60;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
