// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: waveshare43-minimal

#include "../ui.h"

void ui_Cast_screen_init(void)
{
    ui_Cast = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Cast, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button53 = lv_btn_create(ui_Cast);
    lv_obj_set_width(ui_Button53, 100);
    lv_obj_set_height(ui_Button53, 50);
    lv_obj_set_x(ui_Button53, 0);
    lv_obj_set_y(ui_Button53, -5);
    lv_obj_set_align(ui_Button53, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Button53, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button53, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button53, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Button53, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button53, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button53, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label53 = lv_label_create(ui_Button53);
    lv_obj_set_width(ui_Label53, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label53, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label53, "Up");
    lv_obj_set_style_text_font(ui_Label53, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button54 = lv_btn_create(ui_Cast);
    lv_obj_set_width(ui_Button54, 100);
    lv_obj_set_height(ui_Button54, 50);
    lv_obj_set_x(ui_Button54, 0);
    lv_obj_set_y(ui_Button54, 135);
    lv_obj_set_align(ui_Button54, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Button54, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button54, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button54, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label54 = lv_label_create(ui_Button54);
    lv_obj_set_width(ui_Label54, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label54, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label54, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label54, "Down");
    lv_obj_set_style_text_font(ui_Label54, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button55 = lv_btn_create(ui_Cast);
    lv_obj_set_width(ui_Button55, 100);
    lv_obj_set_height(ui_Button55, 50);
    lv_obj_set_x(ui_Button55, -115);
    lv_obj_set_y(ui_Button55, 65);
    lv_obj_set_align(ui_Button55, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Button55, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button55, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button55, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label55 = lv_label_create(ui_Button55);
    lv_obj_set_width(ui_Label55, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label55, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label55, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label55, "Left");
    lv_obj_set_style_text_font(ui_Label55, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button56 = lv_btn_create(ui_Cast);
    lv_obj_set_width(ui_Button56, 100);
    lv_obj_set_height(ui_Button56, 50);
    lv_obj_set_x(ui_Button56, 115);
    lv_obj_set_y(ui_Button56, 65);
    lv_obj_set_align(ui_Button56, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Button56, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button56, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button56, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label56 = lv_label_create(ui_Button56);
    lv_obj_set_width(ui_Label56, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label56, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label56, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label56, "Right");
    lv_obj_set_style_text_font(ui_Label56, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button57 = lv_btn_create(ui_Cast);
    lv_obj_set_width(ui_Button57, 100);
    lv_obj_set_height(ui_Button57, 50);
    lv_obj_set_x(ui_Button57, 0);
    lv_obj_set_y(ui_Button57, 65);
    lv_obj_set_align(ui_Button57, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Button57, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Button57, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button57, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button57, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label57 = lv_label_create(ui_Button57);
    lv_obj_set_width(ui_Label57, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label57, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label57, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label57, "Enter");
    lv_obj_set_style_text_font(ui_Label57, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button58 = lv_btn_create(ui_Cast);
    lv_obj_set_width(ui_Button58, 100);
    lv_obj_set_height(ui_Button58, 50);
    lv_obj_set_x(ui_Button58, 0);
    lv_obj_set_y(ui_Button58, 205);
    lv_obj_set_align(ui_Button58, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Button58, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button58, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button58, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label58 = lv_label_create(ui_Button58);
    lv_obj_set_width(ui_Label58, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label58, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label58, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label58, "Back");
    lv_obj_set_style_text_font(ui_Label58, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button59 = lv_btn_create(ui_Cast);
    lv_obj_set_width(ui_Button59, 100);
    lv_obj_set_height(ui_Button59, 100);
    lv_obj_set_x(ui_Button59, 300);
    lv_obj_set_y(ui_Button59, 65);
    lv_obj_set_align(ui_Button59, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Button59, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button59, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Button59, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button59, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label59 = lv_label_create(ui_Button59);
    lv_obj_set_width(ui_Label59, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label59, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label59, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label59, "Vol Up");
    lv_obj_set_style_text_font(ui_Label59, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button60 = lv_btn_create(ui_Cast);
    lv_obj_set_width(ui_Button60, 100);
    lv_obj_set_height(ui_Button60, 100);
    lv_obj_set_x(ui_Button60, 300);
    lv_obj_set_y(ui_Button60, 180);
    lv_obj_set_align(ui_Button60, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Button60, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button60, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button60, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label60 = lv_label_create(ui_Button60);
    lv_obj_set_width(ui_Label60, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label60, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label60, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label60, "Vol Dn");
    lv_obj_set_style_text_font(ui_Label60, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_Cast);
    lv_obj_set_width(ui_Button2, 80);
    lv_obj_set_height(ui_Button2, 60);
    lv_obj_set_x(ui_Button2, -345);
    lv_obj_set_y(ui_Button2, 190);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);

    ui_Label3 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, 2);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "<");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button53, ui_event_Button53, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button54, ui_event_Button54, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button55, ui_event_Button55, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button56, ui_event_Button56, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button57, ui_event_Button57, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button58, ui_event_Button58, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button59, ui_event_Button59, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button60, ui_event_Button60, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);

}
