// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: waveshare43-minimal

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Main
void ui_Main_screen_init(void);
lv_obj_t * ui_Main;
void ui_event_LEDButton(lv_event_t * e);
lv_obj_t * ui_LEDButton;
lv_obj_t * ui_Label1;
void ui_event_CastButton(lv_event_t * e);
lv_obj_t * ui_CastButton;
lv_obj_t * ui_Label5;


// SCREEN: ui_LEDs
void ui_LEDs_screen_init(void);
lv_obj_t * ui_LEDs;
void ui_event_Button22(lv_event_t * e);
lv_obj_t * ui_Button22;
lv_obj_t * ui_Label22;
void ui_event_Button23(lv_event_t * e);
lv_obj_t * ui_Button23;
lv_obj_t * ui_Label23;
void ui_event_Button24(lv_event_t * e);
lv_obj_t * ui_Button24;
lv_obj_t * ui_Label24;
void ui_event_Button25(lv_event_t * e);
lv_obj_t * ui_Button25;
lv_obj_t * ui_Label25;
void ui_event_Button26(lv_event_t * e);
lv_obj_t * ui_Button26;
lv_obj_t * ui_Label26;
void ui_event_Button27(lv_event_t * e);
lv_obj_t * ui_Button27;
lv_obj_t * ui_Label27;
void ui_event_Button28(lv_event_t * e);
lv_obj_t * ui_Button28;
lv_obj_t * ui_Label28;
void ui_event_Button29(lv_event_t * e);
lv_obj_t * ui_Button29;
lv_obj_t * ui_Label29;
void ui_event_Button30(lv_event_t * e);
lv_obj_t * ui_Button30;
lv_obj_t * ui_Label30;
void ui_event_Button31(lv_event_t * e);
lv_obj_t * ui_Button31;
lv_obj_t * ui_Label31;
void ui_event_Button32(lv_event_t * e);
lv_obj_t * ui_Button32;
lv_obj_t * ui_Label32;
void ui_event_Button33(lv_event_t * e);
lv_obj_t * ui_Button33;
lv_obj_t * ui_Label33;
void ui_event_BackButton1(lv_event_t * e);
lv_obj_t * ui_BackButton1;
lv_obj_t * ui_Label2;


// SCREEN: ui_Cast
void ui_Cast_screen_init(void);
lv_obj_t * ui_Cast;
void ui_event_Button53(lv_event_t * e);
lv_obj_t * ui_Button53;
lv_obj_t * ui_Label53;
void ui_event_Button54(lv_event_t * e);
lv_obj_t * ui_Button54;
lv_obj_t * ui_Label54;
void ui_event_Button55(lv_event_t * e);
lv_obj_t * ui_Button55;
lv_obj_t * ui_Label55;
void ui_event_Button56(lv_event_t * e);
lv_obj_t * ui_Button56;
lv_obj_t * ui_Label56;
void ui_event_Button57(lv_event_t * e);
lv_obj_t * ui_Button57;
lv_obj_t * ui_Label57;
void ui_event_Button58(lv_event_t * e);
lv_obj_t * ui_Button58;
lv_obj_t * ui_Label58;
void ui_event_Button59(lv_event_t * e);
lv_obj_t * ui_Button59;
lv_obj_t * ui_Label59;
void ui_event_Button60(lv_event_t * e);
lv_obj_t * ui_Button60;
lv_obj_t * ui_Label60;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label3;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_LEDButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_LEDs, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_LEDs_screen_init);
    }
}
void ui_event_CastButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Cast, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_Cast_screen_init);
    }
}
void ui_event_Button22(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        DevAccents_OnOff(e);
    }
}
void ui_event_Button23(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Dev56x16_OnOff(e);
    }
}
void ui_event_Button24(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Dev32x8_OnOff(e);
    }
}
void ui_event_Button25(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        DevCube_OnOff(e);
    }
}
void ui_event_Button26(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        DevAccents_Preset1(e);
    }
}
void ui_event_Button27(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Dev56x16_Preset1(e);
    }
}
void ui_event_Button28(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Dev32x8_Preset1(e);
    }
}
void ui_event_Button29(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        DevCube_Preset1(e);
    }
}
void ui_event_Button30(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        DevAccents_Preset2(e);
    }
}
void ui_event_Button31(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Dev56x16_Preset2(e);
    }
}
void ui_event_Button32(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Dev32x8_Preset2(e);
    }
}
void ui_event_Button33(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        DevCube_Preset2(e);
    }
}
void ui_event_BackButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_Main_screen_init);
    }
}
void ui_event_Button53(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        PressUpBtn(e);
    }
}
void ui_event_Button54(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        PressDownBtn(e);
    }
}
void ui_event_Button55(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        PressLeftBtn(e);
    }
}
void ui_event_Button56(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        PressRightBtn(e);
    }
}
void ui_event_Button57(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        PressEnterBtn(e);
    }
}
void ui_event_Button58(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        PressBackBtn(e);
    }
}
void ui_event_Button59(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        PressVolUpBtn(e);
    }
}
void ui_event_Button60(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        PressVolDownBtn(e);
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_Main_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Main_screen_init();
    ui_LEDs_screen_init();
    ui_Cast_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Main);
}
