// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: waveshare43-minimal

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void DevAccents_OnOff(lv_event_t * e);
void Dev56x16_OnOff(lv_event_t * e);
void Dev32x8_OnOff(lv_event_t * e);
void DevCube_OnOff(lv_event_t * e);
void DevAccents_Preset1(lv_event_t * e);
void Dev56x16_Preset1(lv_event_t * e);
void Dev32x8_Preset1(lv_event_t * e);
void DevCube_Preset1(lv_event_t * e);
void DevAccents_Preset2(lv_event_t * e);
void Dev56x16_Preset2(lv_event_t * e);
void Dev32x8_Preset2(lv_event_t * e);
void DevCube_Preset2(lv_event_t * e);
void PressUpBtn(lv_event_t * e);
void PressDownBtn(lv_event_t * e);
void PressLeftBtn(lv_event_t * e);
void PressRightBtn(lv_event_t * e);
void PressEnterBtn(lv_event_t * e);
void PressBackBtn(lv_event_t * e);
void PressVolUpBtn(lv_event_t * e);
void PressVolDownBtn(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
