// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: waveshare43-minimal

#include "ui.h"

void DevAccents_OnOff(lv_event_t * e)
{
	// Your code here
}

void Dev56x16_OnOff(lv_event_t * e)
{
	// Your code here
}

void Dev32x8_OnOff(lv_event_t * e)
{
	// Your code here
}

void DevCube_OnOff(lv_event_t * e)
{
	// Your code here
}

void DevAccents_Preset1(lv_event_t * e)
{
	// Your code here
}

void Dev56x16_Preset1(lv_event_t * e)
{
	// Your code here
}

void Dev32x8_Preset1(lv_event_t * e)
{
	// Your code here
}

void DevCube_Preset1(lv_event_t * e)
{
	// Your code here
}

void DevAccents_Preset2(lv_event_t * e)
{
	// Your code here
}

void Dev56x16_Preset2(lv_event_t * e)
{
	// Your code here
}

void Dev32x8_Preset2(lv_event_t * e)
{
	// Your code here
}

void DevCube_Preset2(lv_event_t * e)
{
	// Your code here
}

void PressUpBtn(lv_event_t * e)
{
	// Your code here
}

void PressDownBtn(lv_event_t * e)
{
	// Your code here
}

void PressLeftBtn(lv_event_t * e)
{
	// Your code here
}

void PressRightBtn(lv_event_t * e)
{
	// Your code here
}

void PressEnterBtn(lv_event_t * e)
{
	// Your code here
}

void PressBackBtn(lv_event_t * e)
{
	// Your code here
}

void PressVolUpBtn(lv_event_t * e)
{
	// Your code here
}

void PressVolDownBtn(lv_event_t * e)
{
	// Your code here
}
